site_name: 3Ztree
nav:
  - 首页: index.md
  - "结点交互": NodeInteraction.md
  - "导航菜单": NavigationMenu.md
  - 配置菜单: ConfigurationMenu.md
  - 创建结点: CreateNode.md
  - 树文件操作: TreeFileOperation.md
  - 连线: Ligature.md
  - 全局操作: GlobalGperation.md
theme:
  name: "readthedocs"
docs_dir: docs

